channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.1.0
  - nbgrader=0.5.5
  - notebook=6.1.4
  - numpy=1.19.3
  - pandas=1.1.4
  - python=3.8.0
  - scikit-learn=0.23.2
  - category_encoders=2.2.2
  - flask=1.1.2
  - peewee=3.13.3
  - psycopg2=2.8.4
  - pip
  - pip:
    - gunicorn==20.0.0
  
